Altinn/altinn-design-system

.eslintignore, .eslintrc.js, .gitattributes, .gitignore, .storybook/StoryPage.tsx, .storybook/main.js, README.md, jest.config.js, package.json, rollup.config.js, scripts/.eslintrc.js, scripts/add-component.mjs, scripts/templates/Component/_COMPONENT_.module.css, scripts/templates/Component/_COMPONENT_.stories.tsx, scripts/templates/Component/_COMPONENT_.test.tsx, scripts/templates/Component/_COMPONENT_.tsx, scripts/templates/Component/index.ts, src/components/Panel/Panel.stories.tsx, src/components/Panel/Panel.test.tsx, src/components/Panel/Panel.tsx, tsconfig.json
This makes it easy to get up and running with new components.
=> feat: add script to bootstrap new components

.storybook/main.js, postcss/revert-rem-values.js
Also updated classname generation for css modules to use better naming, so its a lot easier to inspect stuff in devtools
=> fix: update regex to take windows paths into account

src/components/Button/Button.module.css
fix: set explicit line-height on button, since design system v1 will make the outcome unpredictable
=> fix: set explicit line-height on button, since design system v1 will make the outcome unpredictable

package.json, src/components/AppWrapper/AppWrapper.module.css, src/components/Button/Button.module.css, src/components/CircularProgress/CircularProgress.module.css, src/components/Panel/Panel.module.css, src/components/ToggleButtonGroup/ToggleButton.module.css, src/components/ToggleButtonGroup/ToggleButtonGroup.module.css, yarn.lock
Several variables were renamed in the latest version of figma tokens package. All usages have been updated.
=> chore: update to latest version of design system tokens

.github/workflows/build.yaml
Add [codecov ](https://docs.codecov.com/docs) reports to code
=> chore: add codecov reports

src/components/Button/Button.test.tsx, src/components/Button/Button.tsx, src/components/Panel/Panel.test.tsx, src/components/Panel/Panel.tsx, src/components/TextField/TextField.test.tsx, src/components/TextField/TextField.tsx
check that css classes are present when a certain variant of the component is rendered to ensure correct styles are applied
=> test: improve tests to ensure correct styles are applied

src/components/Accordion/index.ts, src/components/index.ts
Exports new component AccordionIcon
- #91
=> Export new files

.storybook/preview.js
Changed default background color to a darker variant.
=> change default background color

package.json, src/components/Accordion/Accordion.module.css, src/components/Accordion/Accordion.stories.tsx, src/components/Accordion/AccordionHeader.module.css, src/components/Button/Button.module.css, src/components/ToggleButtonGroup/ToggleButton.module.css, src/components/ToggleButtonGroup/ToggleButtonGroup.module.css, yarn.lock
[The figma-design-tokens library](https://github.com/Altinn/figma-design-tokens) has been released with several breaking changes. I have updated the CSS files accordingly.
=> Update Figma-design-tokens to 3.1.0

src/components/Checkbox/Checkbox.module.css, src/components/Checkbox/Checkbox.stories.tsx, src/components/Checkbox/Checkbox.tsx, src/components/CheckboxGroup/CheckboxGroup.module.css, src/components/CheckboxGroup/CheckboxGroup.stories.tsx, src/components/CheckboxGroup/CheckboxGroup.tsx
Fixing the following errors:
- Checkbox should be center-aligned with the first line of the label if it is multiline
- The label shouldn't overlap the checkbox when it becomes too long
- Line height should be set to 1.5 (`--typography-default-line-height`)
- Error checkboxes should not indicate an error when they are checked
- The red error line is not supposed to show up (the sketch wasn't up to date)
Also, I have improved the CSS code to set some internal variables according to the modifier/pseudo class of the wrapper, so the rest of the code don't need to care about that.
=> Fix minor checkbox issues

package.json, src/components/Checkbox/Checkbox.module.css, src/components/CheckboxGroup/CheckboxGroup.module.css, yarn.lock
Update names on existing tokens and add new tokens for top spacing on descriptions.
- #86
- #142
=> Update Figma tokens

package.json, src/components/FieldSet/FieldSet.module.css, yarn.lock
Apply new fieldset space tokens.
=> Implement fieldset space tokens

src/components/Select/Select.module.css, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/TextArea/TextArea.test.tsx, src/components/TextArea/TextArea.tsx, src/components/TextField/TextField.test.tsx, src/components/TextField/TextField.tsx, src/components/_InputWrapper/InputWrapper.module.css, src/components/_InputWrapper/InputWrapper.test.tsx, src/components/_InputWrapper/InputWrapper.tsx
- Moved `onChange` handling for `Select` out of the `useEffect` hook since it became triggered unexpectedly
- Fixed some padding issues (`InputWrapper` should not have padding for `Select`)
- Added `for` attribute to `<label>`
- Added `label` and `hideLabel` properties to `Select`
- #138
=> Fix onChange and label problems

src/components/Button/Button.module.css
Fix font-sizes to comply with figma design, increase quiet button x-padding.
- https://github.com/Altinn/app-frontend-react/pull/641
=> fix font sizes and quiet button padding

docker-compose.yml
=> Upgrading to node v18

src/components/CheckboxGroup/CheckboxGroup.tsx, src/components/FieldSet/FieldSet.tsx, src/components/RadioGroup/RadioGroup.tsx
=> Resolve circular dependency errors

src/components/index.ts
Enums should not be exported as types.
=> Fix enum exports

src/components/Select/Select.module.css
=> Fix scrolling issue in Select

src/components/Pagination/Pagination.tsx, src/components/Table/TableCell.tsx, src/components/Table/TableRow.tsx
Added possibility for screen reader to read sort direction in the table component. 
=> Added UU for ListComponent

README.md
This adds a note in the README describing how to link your project to `altinn-design-system` when developing something in the design system alongside other projects.
=> Note in README about linking

src/components/Table/ResponsiveTable.tsx, src/components/Table/TableCell.tsx
The extra space and padding broke our tests inn app-frontend-react.
=> Fixing minor breakages after Table changes

src/components/TextArea/TextArea.stories.tsx, src/components/TextArea/TextArea.tsx
TextArea has been moved to @digdir/design-system-react and will no longer be updated here.
- #235
=> Add deprecation flag to TextArea

src/components/TextField/TextField.stories.tsx, src/components/TextField/TextField.tsx
This component has been moved to Digdir's common design system.
- #235
=> Add deprecation flag to TextField

README.md
Added link to the common design system and explanation for what will live in the different storybooks.
=> Added link to the common design system

custom.d.ts, src/components/Map/Map.stories.tsx, src/components/Map/Map.test.tsx, src/components/Map/Map.tsx
Made a change to the map component so it animates a fly-to animation when the markerLocation changes.
Fixed storybook stories for the map-component
- #281
=> Map: Added flyTo animation when MarkerLocation changes

src/components/Map/Map.tsx
=> Fixed null check statement

src/components/Page/PageHeader.tsx
Fixes a bug where icon on Page component gets smaller when less space
- #286
=> change page header to set min-height

src/components/CircularProgress/CircularProgress.tsx
Added aria hidden to svg.
- #303
=> Circular Progress: Add aria hidden to svg to avoid error in arc toolkit

src/components/CircularProgress/index.ts, src/components/index.ts
Export circular progress props
=> export circular progress props

docs/intro.mdx
Added link and description for designsystemet.no in introduction in altinn storybook.
- Fixes: https://github.com/digdir/designsystem/issues/10
=> Add link to designsystemet

src/components/Map/Map.tsx
=> Add openstreetmap layer to Map component
