.storybook/StoryPage.css
.storybook/StoryPage.tsx
README.md
src/components/Panel/Panel.module.css
src/components/Panel/Panel.test.tsx
src/components/Panel/Panel.tsx

The old design system sets font-size 62.5% (10px) on HTML element, and the new design system is designed with 100% (16px) as the root font size in mind.
We are using REM's for sizes in the new design system, and this means we need to multiply any size token with 1.6 for the values to mean the same in the new and old design system.
In the long term, we may want to get rid of the 62.5% rule on the HTML element, or we may want to switch the new design system over to also use 62.5% (10px) as the base value instead - we have not decided yet.
We anyway need this temporary fix to be able to use this component in app-frontend code. 
A permanent solution will be discussed/solved in https://github.com/Altinn/altinn-design-system/issues/15

fix: temp override design-system tokens to fix compaitibility with old design system

---

package.json
src/components/TextField/TextField.test.tsx
src/components/TextField/TextField.tsx
yarn.lock

- Spread `rest`-props last
- Spread `rest`-props to `NumberFormat` component as well
- Remove `ariaDescribedBy` prop, this can instead be set with `aria-describedby`
- `NumberFormat` component previously triggered `onChange` on rerender as well, which caused issues since we were trying to overwrite the `value` on the `event.target` which would be null on rerender. Now we only trigger `onChange` if the source of the change is from an event.
- Update peerDependency to require React 18. This was not introduced in this PR, but we have been using React 18 features for a little while now, but forgotten to update this requirement.
- https://github.com/Altinn/app-frontend-react/pull/328

Minor TextField fixes

---

src/components/TextField/TextField.module.css

- Make TextField have a focus outline when focused, even when field is `readonly`, ref https://github.com/Altinn/app-frontend-react/pull/328#issuecomment-1206268388

fix: show focus outline when focusing TextField in readonly mode

---

.gitignore
.storybook/main.js
__mocks__/png.ts
custom.d.ts
jest.config.js
package.json
rollup.config.js
src/components/Map/Map.module.css
src/components/Map/Map.stories.tsx
src/components/Map/Map.test.tsx
src/components/Map/Map.tsx
src/components/Map/index.ts
src/components/index.ts
yarn.lock

Generic map component
Generic map component for selecting a lat/lon location as described in https://github.com/Altinn/altinn-studio/issues/8480
- https://github.com/Altinn/altinn-studio/issues/8480

Map component

---

src/components/Map/Map.test.tsx
src/components/Map/Map.tsx

- fixes issue where map calls onClick even when map is readonly
- minor refactoring:
- move onClick handler to separate component, not related to LocationMarker, since its really tied to the map and not the LocationMarker itself
- reuse types from MapProps to ensure we keep the same interface (optional vs required props f.ex)
- #60

fix: map component calls onClick even when map is readonly

---

src/components/CircularProgress/CircularProgress.tsx

Remove aria-value now because this value had no extra information for screen readers. It only made things worse when the value had many decimals, it would read a long decimal number. The aria label should be good enough for screen reader to understand.
- #125

Fix screen reader bug for circular progress

---

src/components/Checkbox/Checkbox.module.css
src/components/Checkbox/Checkbox.stories.tsx
src/components/Checkbox/Checkbox.test.tsx
src/components/Checkbox/Checkbox.tsx
src/components/CheckboxGroup/CheckboxGroup.module.css
src/components/CheckboxGroup/CheckboxGroup.stories.tsx
src/components/CheckboxGroup/CheckboxGroup.test.tsx
src/components/CheckboxGroup/CheckboxGroup.tsx
src/components/CheckboxGroup/index.ts
src/components/index.ts

Component that groups checkboxes into a multiple choice view. I have also added a `description` prop to the `Checkbox` component, to make it easy to add a description to each checkbox.
- #142

Add CheckboxGroup component

---

src/components/Accordion/AccordionHeader.module.css

Right now, the line height is not set in the accordion header, meaning that the component might look different when in use than it does in storybook. The component shouldn't have an arbitrary look depending on some unknown value. Thus, we set the line-height in the component.
It is set to 16 because that is what the component was designed with.

Set line height in Accordion header

---

src/components/CheckboxGroup/CheckboxGroup.module.css
src/components/CheckboxGroup/CheckboxGroup.tsx
src/components/FieldSet/FieldSet.module.css
src/components/FieldSet/FieldSet.stories.tsx
src/components/FieldSet/FieldSet.test.tsx
src/components/FieldSet/FieldSet.tsx
src/components/FieldSet/index.ts
src/components/index.ts

I have separated the `fieldset` component from the `CheckboxGroup`, so that it can be used other places, like in the future radio button group. It will also be useful in the data modelling part of Altinn Studio. Ideally there would be designated Figma tokens for this, but for now I have just reused the checkbox-related tokens that were used on the `CheckboxGroup`. At the moment checkboxes are the only thing it's used for anyways.
- #155

Add field set component

---

package.json
src/components/TextField/TextField.test.tsx
src/components/TextField/TextField.tsx
yarn.lock

Updated `react-number-format` to a new major version (v5). This contains several breaking changes, so the `TextField` component had to be updated accordingly. Luckily, it looks like it will be fully compatible with app-frontend, so that no changes will be necessary there or in any existing apps. This version fixes the issue mentioned with suffixes; unfortunately, it also introduces a new similar bug also related to suffixes (the other linked issue is related to this).
These new issues have been mitigated by modifying the behavior of the keyDown event in the `numericKeyDown` function. I discovered another issue which was present in the old version as well. If you start a prefix with `-`, a lot of weird behavior occurs since `react-number-format` under the hood checks the first character to …

Updated react-number-format to 5.0.1

---

src/components/Checkbox/Checkbox.stories.tsx
src/components/Checkbox/Checkbox.test.tsx
src/components/Checkbox/Checkbox.tsx

If the checkbox is not supposed to have a visible label, it should still have an `aria-label` on the HTML attribute. I have therefore added a `hideLabel` property that hides the label and adds it to the `aria-label` property instead.

Invisible label on checkbox

---

src/components/Pagination/Pagination.module.css
src/components/Pagination/Pagination.stories.tsx
src/components/Pagination/Pagination.test.tsx
src/components/Pagination/Pagination.tsx
src/components/Pagination/first_page.svg
src/components/Pagination/index.ts
src/components/Pagination/last_page.svg
src/components/Pagination/navigate_before.svg
src/components/Pagination/navigate_next.svg
src/components/Table/Context.ts
src/components/Table/Table.module.css
src/components/Table/Table.stories.module.css
src/components/Table/Table.stories.tsx
src/components/Table/Table.test.tsx
src/components/Table/Table.tsx
src/components/Table/TableBody.module.css
src/components/Table/TableBody.tsx
src/components/Table/TableCell.module.css
src/components/Table/TableCell.tsx
src/components/Table/TableFooter.module.css
src/components/Table/TableFooter.tsx
src/components/Table/TableHeader.module.css
src/components/Table/TableHeader.tsx
src/components/Table/TableRow.module.css
src/components/Table/TableRow.tsx
src/components/Table/index.ts
src/components/Table/sort_arrow.svg
src/components/index.ts

We have added two new components: Table and Pagination. 
Table consists of several parts: Table, TableHeader, TableBody, TableFooter, TableRow and TableCell. Some features: 
- A tablecell will automatically adjust to its wrapper (footer, header, body), but can be overruled by a prop. 
- The table component takes a prop stating if the rows should be selectable. 
- A table header cell/column can be sortable by a prop. 
Pagination component is a simple pagination component. It takes props for dynamic text and to make it possible to connect a table and pagination. 
The table story shows both table and pagination working togheter. 
- #

Add table component with pagination and sorting

---

package.json
src/utils/numberFormat.ts
yarn.lock

Updated `react-number-format` to version 5.1.1. This includes some minor bug-fixes and fixes a typo that had to be changed in the imports. Cypress tests in app-frontend are all green ✅ 
- ~~#{issue number}~~
- ~~Manual testing done (required)~~
- ~~Relevant automated test added (if you find this hard, leave it and we'll help out)~~
- ~~User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)~~

Update react-number-format and fix typo

---

src/components/Button/Button.module.css
src/components/Button/Button.tsx
src/components/Button/Stories/FilledButton.stories.tsx
src/components/Button/Stories/OutlineButton.stories.tsx
src/components/Button/Stories/QuietButton.stories.tsx

After a review of the new button styles with UX resource, som changes were wanted:
- Added Inverted as a new color.
- Added `fullWidth` as an option to make the buttons width to fill its container.
- Added `dashedBorder` as an option to make the outline buttons border-style dashed.
- Fixed issue with outline being set when clicking the button.

add inverted color dashed border full width option

---

src/components/CheckboxGroup/CheckboxGroup.test.tsx
src/components/CheckboxGroup/CheckboxGroup.tsx
src/components/CheckboxGroup/index.ts
src/components/index.ts
src/utils/arrayUtils.test.ts
src/utils/arrayUtils.ts

The `onChange` handler on the checkbox group is now called on first render and sometimes when there are no real changes, since the `useEffect` hook doesn't check the actual values of array dependencies. This pull request should solve this by adding a `useRef` for checking if it is the first render and an `arraysEqual` function to check for differences inside the `checkedNames` array. Also, it exports CheckboxGroupVariant so that it can be used by the consumer.

Fix onChange bug on CheckboxGroup

---

src/components/Button/Button.test.tsx
src/components/Button/Button.tsx
src/components/Button/index.ts
src/components/Panel/PopoverPanel.stories.tsx

Potential Breaking change by using forwardRef:
https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers
Use forwardRef to allow passing a reference to the html button which is needed by the popover component to use the button as a trigger.
Also make variant and color optional as they have default values.
- https://github.com/Altinn/app-frontend-react/issues/439

Support button to be used as popover trigger

---

package.json
yarn.lock

Reverts Altinn/altinn-design-system#170
I was a little quick to push this button since the tests passed, but we should await this change until rollup v3 hits in #169

Revert "chore(deps): update dependency rollup-plugin-dts to v5"

---

src/components/Select/MultiSelectItem.module.css
src/components/Select/Select.module.css
src/components/Select/Select.stories.tsx
src/components/Select/Select.test.tsx
src/components/Select/Select.tsx
src/components/_InputWrapper/InputWrapper.module.css
src/components/_InputWrapper/InputWrapper.test.tsx
src/components/_InputWrapper/InputWrapper.tsx

- Changed `displayName` to `label` to keep naming consistent with the checkbox components (**breaking**)
- Added `value` attributes to relevant elements
- Improved focus styling (had to add a `noFocusEffect` property on `InputWrapper` since multiselect consists of several buttons and handles focus effects itself)
- Made tests look cleaner with regards to the 80 characters restriction
- #138

Improvements on Select component

---

src/components/Button/Button.tsx

Quick fix that merges className from props into button's classNames. Previously providing a custom className would override all styling since the restProps were inserted last.
- https://github.com/Altinn/app-frontend-react/issues/580

Button component: merge provided className

---

src/components/Table/Table.tsx
src/components/Table/TableBody.tsx
src/components/Table/TableCell.tsx
src/components/Table/TableFooter.tsx
src/components/Table/TableHeader.tsx
src/components/Table/TableRow.tsx

In order to make use of the new table-components it is nice to be able to control the props of the different html table-elements. This PR simply extends the components props with the relevant HTMLTableElement-props and passes these through. It also combines the classNames so that custom classes can be added as well.
There should not be any breaking changes from this.
- https://github.com/Altinn/app-frontend-react/issues/580
- ~~Relevant automated test added (if you find this hard, leave it and we'll help out)~~
- ~~All tests run green~~
- ~~User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)~~

Pass through table-props

---

src/components/Select/Select.test.tsx
src/components/Select/Select.tsx
src/components/TextField/TextField.test.tsx
src/components/TextField/TextField.tsx

- Ensure that the input field in `TextField` always has an ID (for labelling purposes) by using the `inputId` argument from `InputWrapper`, and add related tests.
- Group tests related to the default mode for TextField in their own `describe` block.
- Fix `hideLabel` functionality on `Select` and related test that gave a false positive.

Fix labelling issues

---

src/components/Button/Button.test.tsx
src/components/Button/Button.tsx
src/components/Button/Stories/FilledButton.stories.tsx
src/components/Button/Stories/OutlineButton.stories.tsx
src/components/Button/Stories/QuietButton.stories.tsx
src/components/SvgIcon/Stories/SvgIcon.stories.tsx
src/components/SvgIcon/SvgIcon.test.tsx
src/components/SvgIcon/SvgIcon.tsx

Remove iconName property which allowed for inserting an icon with setting iconName to a name of an icon existing in NAV's icon library. The implementation did not allow for treeshaking and added a lot of extra unused data to the bundle as every single icon was added regardless if used or not. 
The way of using Icons with the button is now to import an icon from navikt/ds-icons and pass it to the buttons `icon` property.
```
import { Success as SuccessIcon } from '@navikt/ds-icons';
<Button icon={<SuccessIcon />} />
```

--breaking-change-- remove iconName prop along with functionality

---

src/components/CheckboxGroup/CheckboxGroup.tsx
src/components/Select/Select.tsx
src/components/Tabs/Tabs.module.css
src/components/Tabs/Tabs.stories.tsx
src/components/Tabs/Tabs.test.tsx
src/components/Tabs/Tabs.tsx
src/components/Tabs/index.ts
src/components/index.ts
src/hooks/index.ts
src/hooks/useUpdate.test.ts
src/hooks/useUpdate.ts
src/utils/arrayUtils.test.ts
src/utils/arrayUtils.ts

This pull request adds a tab navigation component similar to the one used in Altinn Studio. It also adds a `useUpdate` hook and a couple of array handling utils. At the moment, there are no Figma tokens related to this component.

Add tabs component

---

src/components/Checkbox/Checkbox.module.css
src/components/Checkbox/Checkbox.test.tsx
src/components/CheckboxGroup/CheckboxGroup.tsx
src/components/FieldSet/FieldSet.module.css
src/components/RadioButton/RadioButton.module.css
src/components/RadioButton/RadioButton.stories.tsx
src/components/RadioButton/RadioButton.test.tsx
src/components/RadioButton/RadioButton.tsx
src/components/RadioButton/index.ts
src/components/RadioGroup/RadioGroup.module.css
src/components/RadioGroup/RadioGroup.stories.tsx
src/components/RadioGroup/RadioGroup.test.tsx
src/components/RadioGroup/RadioGroup.tsx
src/components/RadioGroup/index.ts
src/components/_CheckboxRadioTemplate/CheckboxRadioTemplate.module.css
src/components/_CheckboxRadioTemplate/CheckboxRadioTemplate.test.tsx
src/components/_CheckboxRadioTemplate/CheckboxRadioTemplate.tsx
src/components/index.ts
src/hooks/index.ts
src/hooks/usePrevious.test.ts
src/hooks/usePrevious.ts

The main purpose of this pull request is to add radio buttons to the design system. This includes two new components; `RadioGroup` and `RadioButton`. I have also created a new internal component, `CheckboxRadioTemplate`, which is used as a template for checkboxes and radio buttons since they share a lot of things. I have also copied over the `usePrevious` hook that we use in Altinn Studio, as it is useful in both of the `CheckboxGroup` and `RadioGroup` components. I have used checkbox related Figma tokens, as there are no tokens for radio buttons yet.
- #209

Add radio buttons

---

.storybook/main.js
__mocks__/png.ts
custom.d.ts
jest.config.js
package.json
rollup.config.mjs
src/components/Map/Map.tsx
yarn.lock

The PNG imports in the `Map` component do not seem to be necessary, as they are the same as the ones in the default settings of of the `Marker` component. Removing them will simplify installation of the design system for Webpack users, as they won't have to adjust their configuration.
- #214

Remove PNG imports

---

.storybook/main.js
__mocks__/png.ts
custom.d.ts
jest.config.js
package.json
rollup.config.mjs
src/components/Map/Map.tsx
yarn.lock

Reverts Altinn/altinn-design-system#215
See also:
- #214
This PR broke the Map component when I tested it out in `app-frontend-react`:

Revert "Remove PNG imports"

---

src/components/Tabs/Tabs.module.css
src/components/Tabs/Tabs.stories.tsx
src/components/Tabs/Tabs.test.tsx
src/components/Tabs/Tabs.tsx
src/components/Tabs/index.ts
src/components/index.ts

- Added an optional `value` property to `TabItem`. It's not ideal to use the displayed name to identify tabs in cases where this is a dynamic value.
- Increased the `z-index` values on the tablist and the divider, as the current value (-1) makes the divider hide between background components.
- Removed the `idMap` and put all handling of undefined values in one place. It's a bit cleaner like this.
- #208

Fixes in tabs component

---

src/components/Table/TableRow.tsx

Previously, if `selectRows` is false, and no `rowData` was provided, every row would appear to be selected because `"undefined" === "undefined"` evaluates to true for every row. Additionally, `isSelected` did not require `selectRows` to be `true` in the `TableContext`.
- ~~#{issue number}~~
- ~~[ ] Relevant automated test added (if you find this hard, leave it and we'll help out)~~
- ~~[ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)~~

Table row selection bug

---

README.md
docs/intro.stories.mdx

Added documentation on how to install the designsystem in both the Readme file and the introduction page.
- #224
_It seems like there is a bug making the introduction page blank. I had a quick look into it, but couldn't find any errors in the setup. I suggest we make a separate issue to fix this._

Add documentation on how to install

---

src/components/Map/Map.test.tsx
src/components/Map/Map.tsx

Wrap map component coordinates so only valid coordinates between -90 to 90 for latitude and -180 to 180 for longitude is returned.
- #243

Wrap map component coordinates (#243)

---

src/components/Panel/Panel.module.css

Padding and fontsize for panel is currently only defined for `@media only screen`, so I added a separate styling for `@media print`. 
Panel currently looks like this when printing:
- https://github.com/Altinn/app-frontend-react/issues/710
- https://github.com/Altinn/app-frontend-react/pull/736
-  ~~Relevant automated test added (if you find this hard, leave it and we'll help out)~~
- ~~User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)~~

Add print style for panel

---

.storybook/main.js
__mocks__/png.ts
custom.d.ts
jest.config.js
package.json
rollup.config.mjs
src/components/Map/Map.test.tsx
src/components/Map/Map.tsx
yarn.lock

In #215, png imports were removed in order to make builds easier for projects importing the design system (by not requiring to support png files in their build systems, unless explicitly needed when using the map component). This change was a good step forward, but came at a bad time - breaking [app-frontend-react](https://github.com/Altinn/app-frontend-react/) at a very bad time. Now is the time to clean up and pay this debt, fixing app-frontend-react so the map component works properly - even with this change in the design system.
- #215 
- #216

Re-doing "Remove PNG imports"

---

src/components/Checkbox/Checkbox.test.tsx
src/components/Checkbox/Checkbox.tsx
src/components/CheckboxGroup/CheckboxGroup.test.tsx
src/components/CheckboxGroup/CheckboxGroup.tsx
src/components/FieldSet/FieldSet.test.tsx
src/components/FieldSet/FieldSet.tsx
src/components/RadioButton/RadioButton.test.tsx
src/components/RadioButton/RadioButton.tsx
src/components/RadioGroup/RadioGroup.test.tsx
src/components/RadioGroup/RadioGroup.tsx
src/components/_CheckboxRadioTemplate/CheckboxRadioTemplate.tsx

- Switched type from `string` to `ReactNode` on labels, descriptions and legends related to checkboxes and radio buttons
- Added presentation property to checkbox and radio components for adding a presentation role in preview mode
- https://github.com/digdir/designsystem/issues/32
- https://github.com/Altinn/altinn-studio/issues/9218

React nodes in checkboxes and radio buttons

---

.storybook/DeprecationWarning.tsx
.storybook/StoryPage.tsx
src/components/Button/Button.tsx
src/components/Button/Stories/FilledButton.stories.tsx
src/components/Button/Stories/OutlineButton.stories.tsx
src/components/Button/Stories/QuietButton.stories.tsx
src/components/Checkbox/Checkbox.stories.tsx
src/components/Checkbox/Checkbox.tsx
src/components/CheckboxGroup/CheckboxGroup.stories.tsx
src/components/CheckboxGroup/CheckboxGroup.tsx
src/components/ErrorMessage/ErrorMessage.stories.tsx
src/components/ErrorMessage/ErrorMessage.tsx
src/components/FieldSet/FieldSet.stories.tsx
src/components/FieldSet/FieldSet.tsx
src/components/RadioButton/RadioButton.stories.tsx
src/components/RadioButton/RadioButton.tsx
src/components/RadioGroup/RadioGroup.stories.tsx
src/components/RadioGroup/RadioGroup.tsx
src/components/Select/Select.tsx
src/components/Select/Stories/MultipleSelect.stories.tsx
src/components/Select/Stories/SingleSelect.stories.tsx
src/components/Tabs/Tabs.stories.tsx
src/components/Tabs/Tabs.tsx

Added a new `DeprecationWarning` component to use within the Storybook documentation and added `@deprecated` flags to components that have been moved to the common design system.
- #235

Add deprecation flag to moved components

---

src/components/Table/TableRow.tsx

There's no reason that TableRow should be focusable by tabIndex as default because the content within TableRow will automatically be focusable if they are interactive elements. 
By removing the tabIndex we have the same tab-behaviour as material and bootstrap tables. 
- https://github.com/Altinn/app-frontend-react/issues/830

Fixed WCAG issue with focusable TableRow

---

package.json
yarn.lock

Update Figma tokens to version 6.0.1, fixing error with input height variable.

Update Figma tokens

---

src/components/Accordion/Accordion.stories.tsx
src/components/Accordion/Accordion.tsx

Added deprecation flag to `Accordion`, as it has been moved to Digdir's design system.
- #235

Add deprecation flag to Accordion

---

src/components/Accordion/Accordion.tsx
src/components/Button/Button.tsx
src/components/Checkbox/Checkbox.tsx
src/components/CheckboxGroup/CheckboxGroup.tsx
src/components/ErrorMessage/ErrorMessage.tsx
src/components/FieldSet/FieldSet.tsx
src/components/RadioButton/RadioButton.tsx
src/components/RadioGroup/RadioGroup.tsx
src/components/Select/Select.tsx
src/components/Tabs/Tabs.tsx
src/components/TextArea/TextArea.tsx
src/components/TextField/TextField.tsx
src/components/_CheckboxRadioTemplate/CheckboxRadioTemplate.tsx

Fix Jsdoc syntax to make code tools recognize the `@deprecated` flag.

Fix Jsdoc syntax

---

src/components/Table/TableCell.tsx

Sort arrows did not turn black when active in altinn-app. Fix to see what sortable column is active when there is more than one sortable column.

fix sort arrows list component

---

src/components/List/List.stories.tsx
src/components/List/List.tsx
src/components/Table/Table.stories.tsx
src/components/Table/Table.tsx
src/components/ToggleButtonGroup/ToggleButtonGroup.stories.tsx
src/components/ToggleButtonGroup/ToggleButtonGroup.tsx

Mark components that have been moved to DIgdir's design system as deprecated.
- #235

Mark moved components as deprecated

---

.storybook/main.js
package.json
scripts/templates/Component/_COMPONENT_.stories.tsx
src/components/Accordion/Accordion.stories.tsx
src/components/CircularProgress/CircularProgress.stories.tsx
src/components/List/List.stories.tsx
src/components/Map/Map.stories.tsx
src/components/Page/Page.stories.tsx
src/components/Pagination/Pagination.stories.tsx
src/components/Panel/Panel.stories.tsx
src/components/Panel/PopoverPanel.stories.tsx
src/components/SearchField/SearchField.stories.tsx
src/components/SvgIcon/Stories/SvgIcon.stories.tsx
src/components/Table/Table.stories.tsx
yarn.lock

The `storybook-addon-designs` plugin doesn't support Storybook 7, so it has to be removed before upgrading. We probably don't need it anyways.

Remove storybook-addon-designs plugin

---

src/components/Map/Map.tsx

Bug FIxes:
- Moved the old cache server for Map.tsx to the new one to prevent map component to fetch from outdated and soon-to-be-deleted cache service.

Update map-layers to use the new cache service
